# Change these first
owner: spacemeld # Your GitHub organization or username, where this repository lives
repo: uptime-status # The name of this repository

sites:
  - name: Budding Signers
    url: https://buddingsigners.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.spacemeld.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime Status for Spacemeld
  introTitle: "Uptime monitor and status page, powered entirely by GitHub for Spacemeld."
  introMessage: This lists active sites developed by Spacemeld using **real-time** data via GitHub from Upptime ([GitHub repository](https://github.com/upptime/upptime)). No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
